name: cypress-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: cypress-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18.18.2
        uses: actions/setup-node@v4
        with:
          node-version: 18.18.2

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        env:
          JIRA_CLIENT_ID: ${{ secrets.JIRA_CLIENT_ID }}
          JIRA_CLIENT_SECRET: ${{ secrets.JIRA_CLIENT_SECRET }}
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
          XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
          XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
        run: npm run test:ci
