name: Cypress Tests with Xray

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      # Ejecutar Cypress y generar reporte JUnit sin modificar cypress.config.js
      - name: Run Cypress tests with JUnit reporter
        run: |
          mkdir -p results
          npx cypress run --reporter junit --reporter-options "mochaFile=results/junit-[hash].xml,toConsole=true"

      # Subir reporte a Xray (Jira Cloud)
      - name: Upload results to Xray
        run: |
          echo "Autenticando en Xray..."
          AUTH_RESPONSE=$(curl -s -X POST \
            -H "Content-Type: application/json" \
            -d "{\"client_id\":\"${{ secrets.JIRA_CLIENT_ID }}\",\"client_secret\":\"${{ secrets.JIRA_CLIENT_SECRET }}\"}" \
            ${{ secrets.JIRA_BASE_URL }}/api/v2/authenticate)
          TOKEN=$(echo $AUTH_RESPONSE | tr -d '"')

          echo "Subiendo resultados a Xray..."
          curl -H "Authorization: Bearer $TOKEN" \
               -F "file=@results/junit-*.xml" \
               ${{ secrets.JIRA_BASE_URL }}/api/v2/import/execution/junit
