name: Cypress Tests and Upload to Xray

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests with JUnit reporter
        run: |
          mkdir -p results
          npx cypress run --reporter junit --reporter-options "mochaFile=results/junit-[hash].xml,toConsole=true"

      - name: Merge JUnit reports
        run: |
          npx junit-report-merger --input results --output results/junit-merged.xml
          ls -l results

      - name: Upload results to Xray
        env:
          TOKEN: ${{ secrets.XRAY_TOKEN }}
        run: |
          echo "Autenticando en Xray..."
          curl -H "Authorization: Bearer $TOKEN" \
               -F "file=@results/junit-merged.xml" \
               ${{ secrets.JIRA_BASE_URL }}/api/v2/import/execution/junit
